In [1]:

import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/Iris.csv')

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [5]:
df = df.drop(['Id'],axis=1)

In [6]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
df['Species'] = df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)

In [9]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [10]:
X = df.iloc[ :, :-1]
y = df.iloc[ : , -1]

In [11]:
X.shape

(150, 4)

In [12]:
y.shape

(150,)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=22)

In [14]:
len(X_train),len(y_train)

(120, 120)

In [15]:
len(X_test),len(y_test)

(30, 30)

In [16]:
#give data to KNN

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [18]:
k_odd_values = np.arange(3,51,2)
test_acc_list = []
for i in k_odd_values:
  reg = KNeighborsClassifier(n_neighbors=i)
  reg.fit(X_train,y_train)
  test_acc_list.append(accuracy_score(y_test , reg.predict(X_test)))

print(f"Best K_value : {k_odd_values[np.argmax(test_acc_list)]}")

Best K_value : 3

In [19]:
from sklearn.neighbors import KNeighborsClassifier
reg = KNeighborsClassifier(n_neighbors=3)
reg.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [20]:
predictions=reg.predict(X_train)

In [21]:
predictions

array([0, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2,
       0, 0, 0, 0, 0, 0, 2, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 2, 1, 2, 0,
       1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 0, 2,
       0, 1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0,
       2, 2, 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0,
       1, 0, 0, 2, 1, 2, 2, 0, 2, 2])

In [22]:
train_performance_check = pd.DataFrame()
train_performance_check = X_train.copy()
train_performance_check['Actual_answers'] = y_train
train_performance_check['Model_ans'] = predictions

In [23]:
train_performance_check

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Actual_answers,Model_ans
30,4.8,3.1,1.6,0.2,0,0
31,5.4,3.4,1.5,0.4,0,0
89,5.5,2.5,4.0,1.3,1,1
90,5.5,2.6,4.4,1.2,1,1
55,5.7,2.8,4.5,1.3,1,1
...,...,...,...,...,...,...
102,7.1,3.0,5.9,2.1,2,2
100,6.3,3.3,6.0,2.5,2,2
44,5.1,3.8,1.9,0.4,0,0
132,6.4,2.8,5.6,2.2,2,2
117,7.7,3.8,6.7,2.2,2,2

In [24]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [25]:
confusion_matrix(y_train,predictions)

array([[44,  0,  0],
       [ 0, 37,  3],
       [ 0,  2, 34]])

In [26]:
accuracy_score(y_train,predictions)

0.9583333333333334

In [27]:
print(classification_report(y_train,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        44
           1       0.95      0.93      0.94        40
           2       0.92      0.94      0.93        36

    accuracy                           0.96       120
   macro avg       0.96      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import json

acc = accuracy_score(y_train, predictions)
cm = confusion_matrix(y_train, predictions)
cr = classification_report(y_train,predictions, output_dict=True)

# convert to dictionary
result = {
    "accuracy": acc,
    "confusion_matrix": cm.tolist(),   # numpy -> list
    "classification_report": cr
}

# dump to json
with open("train_KNN.json", "w") as f:
    json.dump(result, f, indent=4)

In [29]:
result

{'accuracy': 0.9583333333333334,
 'confusion_matrix': [[44, 0, 0], [0, 37, 3], [0, 2, 34]],
 'classification_report': {'0': {'precision': 1.0,
   'recall': 1.0,
   'f1-score': 1.0,
   'support': 44.0},
  '1': {'precision': 0.9487179487179487,
   'recall': 0.925,
   'f1-score': 0.9367088607594937,
   'support': 40.0},
  '2': {'precision': 0.918918918918919,
   'recall': 0.9444444444444444,
   'f1-score': 0.9315068493150684,
   'support': 36.0},
  'accuracy': 0.9583333333333334,
  'macro avg': {'precision': 0.9558789558789559,
   'recall': 0.9564814814814815,
   'f1-score': 0.9560719033581874,
   'support': 120.0},
  'weighted avg': {'precision': 0.9585816585816587,
   'recall': 0.9583333333333334,
   'f1-score': 0.9583550083810184,
   'support': 120.0}}}

In [30]:
#test

In [31]:
X_test.shape

(30, 4)

In [32]:
y_test.shape

(30,)

In [33]:
y_test_predictions = reg.predict(X_test)

In [34]:
y_test_predictions

array([0, 2, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 1, 1, 0, 2,
       0, 1, 2, 0, 2, 2, 2, 2])

In [35]:
confusion_matrix(y_test,y_test_predictions)

array([[ 6,  0,  0],
       [ 0, 10,  0],
       [ 0,  1, 13]])

In [36]:
accuracy_score(y_test,y_test_predictions)

0.9666666666666667

In [37]:
print(classification_report(y_test,y_test_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.91      1.00      0.95        10
           2       1.00      0.93      0.96        14

    accuracy                           0.97        30
   macro avg       0.97      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30

In [38]:
#check with own data

In [39]:
X_train.shape

(120, 4)

In [40]:
X_train.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

In [41]:
import warnings
warnings.filterwarnings('ignore')

In [42]:
res = reg.predict([[1.1,1.2,0.2,0.4]])[0]

In [43]:
if res==0:
  print(f'the flower is setosa')
elif res==1:
   print(f'the flower is versicolor')
else:
  print(f'the flower is verginica')

the flower is setosa

In [44]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import json

acc = accuracy_score(y_test, y_test_predictions)
cm = confusion_matrix(y_test,y_test_predictions)
cr = classification_report(y_test,y_test_predictions, output_dict=True)

# convert to dictionary
result = {
    "accuracy": acc,
    "confusion_matrix": cm.tolist(),   # numpy -> list
    "classification_report": cr
}

# dump to json
with open("test_knn.json", "w") as f:
    json.dump(result, f, indent=4)

In [45]:
import pickle

In [46]:
with open('KNN iris_predictions.pkl','wb') as f:
  pickle.dump(reg,f)

In [47]:
# oops
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
import json
import sys

class KNN_Iris:
  def __init__(self,data):

    #reading data and splitting for train and test
    try:
      self.df = pd.read_csv(data)
      self.df = self.df.drop('Id',axis=1)
      self.df['Species'] = self.df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)
      self.x = self.df.iloc[:,:-1]
      self.y = self.df.iloc[:,-1]
      self.x_train, self.x_test, self.y_train, self.y_test = train_test_split(
                  self.x, self.y, test_size=0.2, random_state=22)
    except Exception:
            err_ty, err_ms, err_line = sys.exc_info()
            print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

  def training(self):
    try:

      #finding best k value
      K_value = np.arange(3,51,2)
      list_of_acc = []
      from sklearn.neighbors import KNeighborsClassifier
      from sklearn.metrics import accuracy_score
      for i in K_value:
        reg = KNeighborsClassifier(n_neighbors=i)
        reg.fit(self.x_train,self.y_train)
        train_pred = reg.predict(self.x_train)
        list_of_acc.append(accuracy_score(self.y_train,train_pred))
      print(list_of_acc)
      self.x = int(K_value[np.argmax(list_of_acc)])
      print(f'The Best K_Value is : {self.x}')
      print()

      #Give Data to KNN
      from sklearn.neighbors import KNeighborsClassifier
      self.reg = KNeighborsClassifier(n_neighbors=self.x)
      self.reg.fit(self.x_train,self.y_train)

      #Train Performance
      print('--------------Training Performance------------')
      train_prediction = self.reg.predict(self.x_train)
      print(confusion_matrix(self.y_train,train_prediction))
      print('========================================')
      print(accuracy_score(self.y_train,train_prediction))
      print('========================================')
      print(classification_report(self.y_train,train_prediction))
      print()

      #train_data to dictionary format
      acc = accuracy_score(self.y_train,train_prediction)
      conf_mat = confusion_matrix(self.y_train,train_prediction)
      train_report = classification_report(self.y_train,train_prediction,output_dict=True)
      train_data = {'Accuracy_Score':acc,'Confusion_matrix':conf_mat.tolist(),'Classification_report':train_report}

      #dump to json
      with open('train_knn.json','w') as td:
        json.dump(train_data,td,indent=4)

    except Exception:
        err_ty, err_ms, err_line = sys.exc_info()
        print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

  def testing(self):
    try:

      #test performance
      print('--------------Testing Performance------------')
      test_prediction = self.reg.predict(self.x_test)
      print(confusion_matrix(self.y_test,test_prediction))
      print('========================================')
      print(accuracy_score(self.y_test,test_prediction))
      print('========================================')
      print(classification_report(self.y_test,test_prediction))
      print()

      #test_data to dictionary format
      accuracy = accuracy_score(self.y_test,test_prediction)
      confus_mat = confusion_matrix(self.y_test,test_prediction)
      test_report = classification_report(self.y_test,test_prediction,output_dict=True)
      test_data = {'Accuracy_Score':accuracy,'Confusion_matrix':confus_mat.tolist(),'Classification_report':test_report}

      #dump to json
      with open('test_knn.json','w') as test:
        json.dump(test_data,test,indent=4)

    except Exception:
      err_ty, err_ms, err_line = sys.exc_info()
      print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

  def check(self):
    try:
      import warnings
      warnings.filterwarnings('ignore')

      r = self.reg.predict([[2.5,2.8,1.2,1.3]])[0]
      if r == 0:
        print(f'Flower is: Setosa')
      elif r == 1:
        print(f'Flower is: Versicolor')
      else:
        print(f'Flower is: Verginica')

      #creating pickle file
      import pickle
      with open('KNN.pkl','wb') as KNN:
        pickle.dump(self.reg,KNN)
    except Exception:
      err_ty, err_ms, err_line = sys.exc_info()
      print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

if __name__ == "__main__":
  obj = KNN_Iris('/content/Iris.csv')
  obj.training()
  obj.testing()
  obj.check()

[0.9583333333333334, 0.975, 0.975, 0.975, 0.975, 0.975, 0.975, 0.9583333333333334, 0.9583333333333334, 0.95, 0.9666666666666667, 0.9583333333333334, 0.95, 0.9583333333333334, 0.95, 0.975, 0.95, 0.9416666666666667, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.925, 0.9166666666666666]
The Best K_Value is : 5

--------------Training Performance------------
[[44  0  0]
 [ 0 38  2]
 [ 0  1 35]]
========================================
0.975
========================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        44
           1       0.97      0.95      0.96        40
           2       0.95      0.97      0.96        36

    accuracy                           0.97       120
   macro avg       0.97      0.97      0.97       120
weighted avg       0.98      0.97      0.98       120


--------------Testing Performance------------
[[ 6  0  0]
 [ 0 10  0]
 [ 0  1 13]]
========================================
0.9666666666666667
========================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.91      1.00      0.95        10
           2       1.00      0.93      0.96        14

    accuracy                           0.97        30
   macro avg       0.97      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30


Flower is: Setosa