In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/Position_Salaries.csv')

In [3]:
df

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [4]:
df.shape

(10, 3)

In [5]:
df['Position'].unique()

array(['Business Analyst', 'Junior Consultant', 'Senior Consultant',
       'Manager', 'Country Manager', 'Region Manager', 'Partner',
       'Senior Partner', 'C-level', 'CEO'], dtype=object)

In [6]:
df['Position'].value_counts()

Position
Business Analyst     1
Junior Consultant    1
Senior Consultant    1
Manager              1
Country Manager      1
Region Manager       1
Partner              1
Senior Partner       1
C-level              1
CEO                  1
Name: count, dtype: int64

In [7]:
df['Position'] = df['Position'].map({'Business Analyst':0,'Junior Consultant':1,'Senior Consultant':2,'Manager':3,
                                     'Country Manager':4,'Region Manager':5,'Partner':6,
                                     'Senior Partner':7,'C-level':8,'CEO':9}).astype(int)

In [8]:
df['Position']

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Position, dtype: int64

In [9]:
df

   Position  Level   Salary
0         0      1    45000
1         1      2    50000
2         2      3    60000
3         3      4    80000
4         4      5   110000
5         5      6   150000
6         6      7   200000
7         7      8   300000
8         8      9   500000
9         9     10  1000000

In [10]:
x = df.iloc[ : , : -1]
y = df.iloc[: , -1]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
len(X_train),len(y_train)

(8, 8)

In [14]:
len(X_test),len(y_test)

(2, 2)

In [18]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [19]:
reg.coef_

array([43943.96551724, 43943.96551724])

In [20]:
reg.intercept_

np.float64(-196314.6551724139)

In [ ]:
#train

In [21]:
y_train_predictions = reg.predict(X_train)

In [23]:
from sklearn.metrics import root_mean_squared_error,r2_score

In [26]:
print(f'training loss:{root_mean_squared_error(y_train,y_train_predictions)}')
print(f'train accuracy:{r2_score(y_train,y_train_predictions)}')

training loss:178793.92696332146
train accuracy:0.6366049276570866

In [ ]:
#test

In [27]:
y_test_predictions = reg.predict(X_test)

In [28]:
print(f'testing loss:{root_mean_squared_error(y_test,y_test_predictions)}')
print(f'test accuracy:{r2_score(y_test,y_test_predictions)}')

testing loss:88544.09867029046
test accuracy:0.8451346684575973

In [29]:
#oops


import sys
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error,r2_score

In [33]:

class MLR:
  def __init__(self,data):
    try:
      self.df = pd.read_csv(data)
      self.df['Position'] = self. df['Position'].map({'Business Analyst':0,'Junior Consultant':1,'Senior Consultant':2,'Manager':3,
                                     'Country Manager':4,'Region Manager':5,'Partner':6,
                                     'Senior Partner':7,'C-level':8,'CEO':9}).astype(int)
      self.x = self.df.iloc[ : , : -1]
      self.y = self.df.iloc[ : ,-1]
      self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(self.x, self.y, test_size=0.2, random_state=42)

    except Exception as e:
      err_ty,err_ms,err_line = sys.exc_info()
      print(f'Error is due to : {err_ty} from Line No : {err_line.tb_lineno}')

  def training(self):
    try:
      self.reg = LinearRegression()
      self.reg.fit(self.X_train,self.y_train)
      self.y_train_predictions = self.reg.predict(self.X_train)
      print(f'Train Loss : {root_mean_squared_error(self.y_train , self.y_train_predictions)}')
      print(f'Train Accuracy : {r2_score(self.y_train , self.y_train_predictions)}')
    except Exception as e:
      err_ty,err_ms,err_line = sys.exc_info()
      print(f'Error is due to : {err_ty} from Line No : {err_line.tb_lineno}')

  def testing(self):
    try:
      self.y_test_predictions = self.reg.predict(self.X_test)
      print(f'Test Loss : {root_mean_squared_error(self.y_test , self.y_test_predictions)}')
      print(f'Test Accuracy : {r2_score(self.y_test , self.y_test_predictions)}')
    except Exception as e:
      err_ty,err_ms,err_line = sys.exc_info()
      print(f'Error is due to : {err_ty} from Line No : {err_line.tb_lineno}')

  def check(self):
    try:
      Position = 5
      Level = 5
      print(f'Total salary : {self.reg.predict([[Position,Level]])[0]}')
    except Exception as e:
      err_ty,err_ms,err_line = sys.exc_info()
      print(f'Error is due to : {err_ty} from Line No : {err_line.tb_lineno}')

if __name__ == "__main__":
  obj = MLR('/content/Position_Salaries.csv')
  obj.training()
  obj.testing()
  obj.check()

Train Loss : 178793.92696332146
Train Accuracy : 0.6366049276570866
Test Loss : 88544.09867029046
Test Accuracy : 0.8451346684575973
Total salary : 243125.0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(