In [ ]:
import pandas as pd
import numpy as np
import sklearn

In [ ]:
df = pd.read_csv('/content/Iris.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df = df.drop(['Id'],axis = 1)

In [ ]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
df['Species'] = df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)

In [ ]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [ ]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
len(X_train),len(y_train)

(120, 120)

In [ ]:
len(X_test),len(y_test)

(30, 30)

In [ ]:
from sklearn.naive_bayes import GaussianNB
reg = GaussianNB()
reg.fit(X_train,y_train)

GaussianNB()

In [ ]:
#train performance

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
predictions = reg.predict(X_train)

In [ ]:
confusion_matrix(y_train,predictions)

array([[40,  0,  0],
       [ 0, 38,  3],
       [ 0,  3, 36]])

In [ ]:
accuracy_score(y_train,predictions)

0.95

In [ ]:
print(classification_report(y_train,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.93      0.93      0.93        41
           2       0.92      0.92      0.92        39

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import json

acc = accuracy_score(y_train, predictions)
cm = confusion_matrix(y_train, predictions)
cr = classification_report(y_train,predictions, output_dict=True)

# convert to dictionary
result = {
    "accuracy": acc,
    "confusion_matrix": cm.tolist(),   # numpy -> list
    "classification_report": cr
}

# dump to json
with open("train_Naive Bayes.json", "w") as f:
    json.dump(result, f, indent=4)

In [ ]:
#test predictions

In [ ]:
X_test.shape

(30, 4)

In [ ]:
y_test_predictions = reg.predict(X_test)

In [ ]:
accuracy_score(y_test,y_test_predictions)

1.0

In [ ]:
confusion_matrix(y_test,y_test_predictions)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [ ]:
print(classification_report(y_test,y_test_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import json

acc = accuracy_score(y_test, y_test_predictions)
cm = confusion_matrix(y_test,y_test_predictions)
cr = classification_report(y_test,y_test_predictions, output_dict=True)

# convert to dictionary
result = {
    "accuracy": acc,
    "confusion_matrix": cm.tolist(),   # numpy -> list
    "classification_report": cr
}

# dump to json
with open("test_Naive Bayes.json", "w") as f:
    json.dump(result, f, indent=4)

In [ ]:
import pickle

In [ ]:
with open('Naive Bayes.pkl','wb') as f:
  pickle.dump(reg,f)

In [ ]:
#oops

import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.naive_bayes import GaussianNB
import pickle
import json
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
import json
import sys

class Naives_Iris:
  def __init__(self,data):

    #reading data and splitting for train and test
    try:
      self.df = pd.read_csv(data)
      self.df = self.df.drop('Id',axis=1)
      self.df['Species'] = self.df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)
      self.x = self.df.iloc[:,:-1]
      self.y = self.df.iloc[:,-1]
      self.x_train, self.x_test, self.y_train, self.y_test = train_test_split(
                  self.x, self.y, test_size=0.2, random_state=42)
    except Exception:
            err_ty, err_ms, err_line = sys.exc_info()
            print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

  def training(self):
    try:
      #Give Data to Naive Bayes
      from sklearn.naive_bayes import GaussianNB
      self.reg = GaussianNB()
      self.reg.fit(self.x_train,self.y_train)

      #Train Performance
      print('--------------Training Performance------------')
      train_prediction = self.reg.predict(self.x_train)
      print(confusion_matrix(self.y_train,train_prediction))
      print('========================================')
      print(accuracy_score(self.y_train,train_prediction))
      print('========================================')
      print(classification_report(self.y_train,train_prediction))
      print()

      #train_data to dictionary format
      acc = accuracy_score(self.y_train,train_prediction)
      conf_mat = confusion_matrix(self.y_train,train_prediction)
      train_report = classification_report(self.y_train,train_prediction,output_dict=True)
      train_data = {'Accuracy_Score':acc,'Confusion_matrix':conf_mat.tolist(),'Classification_report':train_report}

      #dump to json
      with open('train_Naives.json','w') as td:
        json.dump(train_data,td,indent=4)

    except Exception:
        err_ty, err_ms, err_line = sys.exc_info()
        print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

  def testing(self):
    try:

      #test performance
      print('--------------Testing Performance------------')
      test_prediction = self.reg.predict(self.x_test)
      print(confusion_matrix(self.y_test,test_prediction))
      print('========================================')
      print(accuracy_score(self.y_test,test_prediction))
      print('========================================')
      print(classification_report(self.y_test,test_prediction))
      print()

      #test_data to dictionary format
      accuracy = accuracy_score(self.y_test,test_prediction)
      confus_mat = confusion_matrix(self.y_test,test_prediction)
      test_report = classification_report(self.y_test,test_prediction,output_dict=True)
      test_data = {'Accuracy_Score':accuracy,'Confusion_matrix':confus_mat.tolist(),'Classification_report':test_report}

      #dump to json
      with open('test_Naives.json','w') as test:
        json.dump(test_data,test,indent=4)

    except Exception:
      err_ty, err_ms, err_line = sys.exc_info()
      print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

  def check(self):
    try:
      import warnings
      warnings.filterwarnings('ignore')

      r = self.reg.predict([[2.5,2.8,1.2,1.3]])[0]
      if r == 0:
        print(f'Flower is: Setosa')
      elif r == 1:
        print(f'Flower is: Versicolor')
      else:
        print(f'Flower is: Verginica')

      #creating pickle file
      import pickle
      with open('Naive Bayes.pkl','wb') as f:
        pickle.dump(self.reg,f)
    except Exception:
      err_ty, err_ms, err_line = sys.exc_info()
      print(f"Error is due to : {err_ty} from Line No : {err_line.tb_lineno} and msg is {err_ms}")

if __name__ == "__main__":
  obj = Naives_Iris('/content/Iris.csv')
  obj.training()
  obj.testing()
  obj.check()

--------------Training Performance------------
[[40  0  0]
 [ 0 38  3]
 [ 0  3 36]]
========================================
0.95
========================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.93      0.93      0.93        41
           2       0.92      0.92      0.92        39

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120


--------------Testing Performance------------
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
========================================
1.0
========================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Flower is: Versicolor